export const GITHUB_URL = 'https://github.com/frontendmu?ref=frontend.mu'
export const DISCORD_URL = 'https://discord.gg/WxXW9Jvv6k?ref=frontend.mu'
export const WHATSAPP_URL = 'https://chat.whatsapp.com/CqXAj6m8NtQB6NN8B9aoEJ'
export const TWITTER_URL = 'https://twitter.com/frontendmu?ref=frontend.mu'
export const INSTAGRAM_URL = 'https://www.instagram.com/frontend.mu/?ref=frontend.mu'
export const LINKEDIN_URL = 'https://www.linkedin.com/company/frontendmu/?ref=frontend.mu'
