name: Directus Data Sync

on:
  repository_dispatch:
    types: [directus-data-update]
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  sync-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: |
          cd packages/frontendmu-data
          pnpm install --frozen-lockfile

      - name: Build data
        run: pnpm run data build

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain packages/frontendmu-data/data/)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in data files"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in data files"
          fi

      - name: Create or Update Pull Request
        if: steps.changes.outputs.changes == 'true'
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Fixed branch name for CMS updates
          BRANCH_NAME="cms/data-updates"
          COMMIT_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          
          # Check if branch already exists
          if git ls-remote --exit-code --heads origin "${BRANCH_NAME}"; then
            echo "Branch ${BRANCH_NAME} exists, updating existing PR"
            # Switch to existing branch and pull latest
            git fetch origin "${BRANCH_NAME}"
            git checkout "${BRANCH_NAME}"
            git merge origin/main --no-edit
          else
            echo "Creating new branch ${BRANCH_NAME}"
            # Create new branch from main
            git checkout -b "${BRANCH_NAME}"
          fi
          
          # Add all changes in the data directory
          git add packages/frontendmu-data/data/
          
          # Create commit with timestamp
          git commit -m "(cms): data updated ${COMMIT_TIMESTAMP}"
          
          # Push the branch
          git push origin "${BRANCH_NAME}"
          
          # Check if PR already exists, if not create one
          if ! gh pr view "${BRANCH_NAME}" > /dev/null 2>&1; then
            echo "Creating new pull request"
            gh pr create \
              --title "(cms): data updates" \
              --body "Automated data sync from Directus CMS.

          **Latest update:** ${COMMIT_TIMESTAMP}

          This PR contains automated updates from Directus collections. Each commit represents a data sync triggered by CMS changes.
          
          This PR will be updated automatically when new data changes are detected." \
              --head "${BRANCH_NAME}" \
              --base main
          else
            echo "Pull request already exists, updated with new commit"
            # Update PR body with latest timestamp
            gh pr edit "${BRANCH_NAME}" \
              --body "Automated data sync from Directus CMS.

          **Latest update:** ${COMMIT_TIMESTAMP}

          This PR contains automated updates from Directus collections. Each commit represents a data sync triggered by CMS changes.
          
          This PR will be updated automatically when new data changes are detected."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No changes summary
        if: steps.changes.outputs.changes == 'false'
        run: echo "No data changes detected. Repository is up to date."
